=== CalligherIV/XML_Pendientes/PRÁCTICAS  PENDIENTES XML/XML 3.8 y 3.9/conferencias.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="centroConferencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="salas" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sala" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string"/>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="capacidad" type="xs:int"/>
                    <xs:element name="ubicacion" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="reservas" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="reserva" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string"/>
                    <xs:element name="salaId" type="xs:string"/>
                    <xs:element name="cliente" type="xs:string"/>
                    <xs:element name="fechaInicio" type="xs:date"/>
                    <xs:element name="fechaFin" type="xs:date"/>
                    <xs:element name="asistentes">
                      <xs:simpleType>
                        <xs:restriction base="xs:int">
                          <xs:minInclusive value="1"/>
                          <xs:maxInclusive value="200"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="proyector" type="xs:boolean"/>
                    <xs:element name="comentarios" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CalligherIV/XML_Pendientes/PRÁCTICAS  PENDIENTES XML/XML 3.8 y 3.9/conferencias.xml
<?xml version="1.0" encoding="UTF-8"?>
<centroConferencias xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="conferencias.xsd">
  <salas>
    <sala>
      <id>SALA001</id>
      <nombre>Sala Picasso</nombre>
      <capacidad>100</capacidad>
      <ubicacion>Planta 1</ubicacion>
    </sala>
    <sala>
      <id>SALA002</id>
      <nombre>Sala Velázquez</nombre>
      <capacidad>60</capacidad>
      <ubicacion>Planta 2</ubicacion>
    </sala>
  </salas>
  <reservas>
    <reserva>
      <id>RES001</id>
      <salaId>SALA001</salaId>
      <cliente>Ana Torres</cliente>
      <fechaInicio>2025-06-01</fechaInicio>
      <fechaFin>2025-06-01</fechaFin>
      <asistentes>75</asistentes>
      <proyector>true</proyector>
      <comentarios>Presentación de producto</comentarios>
    </reserva>
    <reserva>
      <id>RES002</id>
      <salaId>SALA002</salaId>
      <cliente>Javier López</cliente>
      <fechaInicio>2025-06-02</fechaInicio>
      <fechaFin>2025-06-02</fechaFin>
      <asistentes>40</asistentes>
      <proyector>false</proyector>
    </reserva>
  </reservas>
</centroConferencias>
