=== CalligherIV/XML_Pendientes/PRÁCTICAS  PENDIENTES XML/XML 3.10/aranceles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="arancel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tipo" type="xs:string"/>
                <xs:element name="valor" type="xs:decimal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pais">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="arancel" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipo" type="xs:string"/>
                            <xs:element name="valor" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="aranceles">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pais" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="arancel" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo" type="xs:string"/>
                                        <xs:element name="valor" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== CalligherIV/XML_Pendientes/PRÁCTICAS  PENDIENTES XML/XML 3.10/aranceles.xml
<?xml version="1.0" encoding="UTF-8"?>
<aranceles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="aranceles.xsd">
    <pais>
        <nombre>China</nombre>
        <arancel>
            <tipo>Porcentaje</tipo>
            <valor>25</valor>
        </arancel>
    </pais>
    <pais>
        <nombre>Unión Europea</nombre>
        <arancel>
            <tipo>Porcentaje</tipo>
            <valor>10</valor>
        </arancel>
    </pais>
    <pais>
        <nombre>Canadá</nombre>
        <arancel>
            <tipo>Porcentaje</tipo>
            <valor>15</valor>
        </arancel>
    </pais>
    <pais>
        <nombre>México</nombre>
        <arancel>
            <tipo>Cantidad</tipo>
            <valor>300</valor>
        </arancel>
    </pais>
</aranceles>
