=== CalligherIV/XML_Pendientes/PRÁCTICAS  PENDIENTES XML/XML 3.6/catalogo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="catalogo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="producto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="precio">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minExclusive value="0"/>
                    <xs:maxExclusive value="200"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="disponible" type="xs:boolean"/>
              <xs:element name="categoria">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="ElectrÃ³nica"/>
                    <xs:enumeration value="Ropa"/>
                    <xs:enumeration value="Hogar"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:positiveInteger"/>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CalligherIV/XML_Pendientes/PRÁCTICAS  PENDIENTES XML/XML 3.6/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogo.xsd">

  <producto id="101">
    <nombre>Auriculares Bluetooth</nombre>
    <precio>59.99</precio>
    <disponible>true</disponible>
    <categoria>Electrónica</categoria>
    <descripcion>Cancelación de ruido, batería 20h</descripcion>
  </producto>

  <producto id="102">
    <nombre>Camiseta Algodón</nombre>
    <precio>19.95</precio>
    <disponible>false</disponible>
    <categoria>Ropa</categoria>
  </producto>

  <producto id="103">
    <nombre>Lámpara LED</nombre>
    <precio>35.50</precio>
    <disponible>true</disponible>
    <categoria>Hogar</categoria>
    <descripcion>Luz cálida, ajustable con mando</descripcion>
  </producto>

</catalogo>
